More liberal regex check for uploaded filenames
CERT-Polska/drakvuf-sandbox pull request #239
Opened 2020-09-25 07:14 UTC by kscieslinski

Solves:  #237 
It's now possible to upload files with filenames containing dots and dashes. For example: `invoice.pdf.exe`, `sample-1.exe`.

2020-09-25 08:04 UTC, icedevml reviewed
What about other special characters?

2020-09-27 19:26 UTC, icedevml requested changes
I would allow all printable characters except special ones to avoid introducing security risks:

```
\
/
>
<
|
:
&
```

2020-09-30 08:38 UTC, kscieslinski commented
> I would allow all printable characters except special ones to avoid introducing security risks:
> 
> ```
> \
> /
> >
> <
> |
> :
> &
> ```

Not sure if we want to rely on regex when it comes to security:) However I agree it's good idea to disallow usage of these characters. I've added the same check to `app.py` to stay consistent.

2020-09-30 11:07 UTC, icedevml approved these changes

2020-10-07 13:59 UTC, merged