Fix's for typo in MultipleProcessesReturned exception
CERT-Polska/drakvuf-sandbox pull request #669
Opened 2021-11-16 13:24 UTC by psrok1

Fixed misplaced `s` in `MultipleProcessesReturned` message and variable name :snake:

2021-11-16 13:27 UTC, nazywam approved these changes

2021-11-16 16:44 UTC, catsuryuu commented on drakcore/drakcore/postprocess/pstree.py
> +        process_str = ", ".join([str(p) for p in processes])
Accurate variable name should be `processes_str` in this exception.

2021-11-22 01:38 UTC, catsuryuu requested changes
https://github.com/CERT-Polska/drakvuf-sandbox/pull/669/files#r750466959

2022-04-08 10:57 UTC, BonusPlay commented
At this point maybe it should stay for the memes :p

2022-04-08 10:57 UTC, closed without merging